### ISSUE TITLE
Option 'unique' considered illegal

### ISSUE THREAD

**Issue by rethab** [joereynolds/gauxilium#106]
I have a statement
```sql
CREATE UNIQUE INDEX ..
```
which is valid SQL, but this linter seems to reject it:

```
init.sql:68 [sql-lint: invalid-create-option] Option 'unique' is not a valid option, must be one of '["algorithm","database","definer","event","function","index","procedure","server","table","tablespace","temporary","trigger","user","view"]'.
```

**Comment by joereynolds** [comment]
Interesting, I'll look into it!

**Comment by joereynolds** [comment]
Pushed up a change to the `typescript` branch (i.e. the main branch) let me know if that sorts it!

**Comment by rethab** [comment]
Thanks! That error disappeared, but now I get a new one:

```
~/dev/sql-lint$ sql-lint -f ../init.sql 
/home/rethab/dev/sql-lint/node_modules/pg-query-stream/index.js:105
  this.connection.sync()
                  ^

TypeError: Cannot read property 'sync' of undefined
    at PostgresQuery.QueryStream.handleError (/home/rethab/dev/sql-lint/node_modules/pg-query-stream/index.js:105:19)
    at PostgresQuery.handleError (/home/rethab/dev/sql-lint/node_modules/any-db-postgres/index.js:84:27)
    at process.nextTick (/home/rethab/dev/sql-lint/node_modules/pg/lib/client.js:63:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

My config file:
```json
{
	"driver": "postgres",
	"host": "localhost",
	"user": "postgres"
}

```

**Comment by joereynolds** [comment]
Hmmm, I think `driver` needs to be `psql` not `postgres` :+1: 

Update: This is incorrect. It does need to be postgres.

**Comment by rethab** [comment]
With `psql`, I get this error:

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'any-db-psql'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at getAdapter (/home/rethab/dev/sql-lint/node_modules/any-db/index.js:27:10)
    at Object.connect [as createConnection] (/home/rethab/dev/sql-lint/node_modules/any-db/index.js:14:17)
    at new Database (/home/rethab/dev/sql-lint/dist/src/database.js:6:33)
    at Object.<anonymous> (/home/rethab/dev/sql-lint/dist/src/main.js:58:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by joereynolds** [comment]
Hey @rethab, I've opened a new issue to track this in. Cheers

**Comment by rethab** [comment]
Great stuff @joereynolds . Let me know if I can test anything
