### ISSUE TITLE
sql-lint fails if not ran from specific directory

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/gauxilium#121]
Not sure if this is just a local issue and various sql-lints conflicting with eachother. Either way, we should take a look. Here's the error

```
: echo "test;" | sql-lint-linux 
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir './src/checker/checks'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (pkg/prelude/bootstrap.js:787:35)
    at CheckerRunner.run (/snapshot/sql-lint/dist/src/checker/checkerRunner.js:13:27)
    at Object.<anonymous> (/snapshot/sql-lint/dist/src/main.js:60:8)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (module.js:662:10)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)

```

It's reproducible by downloading the executable and trying to run it anywhere outside of the `sql-lint` directory.

**Comment by RealOrangeOne** [comment]
I get this error too running off npm, so I don't think it's something isolated.

**Comment by joereynolds** [comment]
Hey @RealOrangeOne 

I believe this issue has been fixed in the executables (the recommended way of running it), let me know if there are still problems, cheers!

https://github.com/joereynolds/sql-lint/commit/1cf25f8331ac4a0ad160ffa5da8cc35bcf42324f
