### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir './src/checker/checks'

### ISSUE THREAD

**Issue by amitkarpe** [joereynolds/gauxilium#126]
Hi @joereynolds 

Found an error for version 0.0.12

```
$ /bin/cat ~/.config/sql-lint/config.json
{
    "driver": "mysql",
    "host": "0.0.0.0",
    "user": "root",
    "password": "pass",
    "port": 3306
}
$ sql-lint -V
0.0.12

$ sql-lint -f create.sql
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir './src/checker/checks'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (pkg/prelude/bootstrap.js:787:35)
    at CheckerRunner.run (/snapshot/sql-lint/dist/src/checker/checkerRunner.js:13:27)
    at Object.<anonymous> (/snapshot/sql-lint/dist/src/main.js:60:8)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (module.js:662:10)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)

$ cd ../..
$ ls src/checker/checks
databaseNotFound.ts    invalidCreateOption.ts  invalidLimitQuantifier.ts  invalidTruncateOption.ts  mySqlError.ts    tableNotFound.ts
invalidAlterOption.ts  invalidDropOption.ts    invalidOption.ts           missingWhere.ts           oddCodePoint.ts  unmatchedParentheses.ts
$ ls test/test-files/
README.md  create.sql  insert.sql  select.sql  stored-procedure.sql  test.sql
$ sql-lint -f test/test-files/create.sql
test/test-files/create.sql:1 [ER_PARSE_ERROR] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE t1 (year YEAR(4), month INT(2) UNSIGNED ZEROFILL, day INT(2) UNSIGN' at line 1

```

When "src/checker/checks" directory is available then it works without any issue but otherwise, it will fail to find "src/checker/checks" gives the following error:
`Error: ENOENT: no such file or directory, scandir './src/checker/checks'`

**Comment by joereynolds** [comment]
Hey @amitkarpe, this was fixed in v.0.0.13
Download it from the releases page and try it out.
Cheers
