### ISSUE TITLE
Hide/Tidy errors from nearley for bad statements

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/gauxilium#129]
In nearley, if something doesn't match the grammar we've provided, we get back a trace like this

```
: ./dist/src/main.js -q "DROP ;"
/home/joe/code/me/sql-lint/node_modules/nearley/lib/nearley.js:320
                throw err;
                ^

Error: Syntax error at line 1 col 6:

  DROP ;
       ^
Unexpected ";". Instead, I was expecting to see one of the following:

A character matching /[ \t\n\v\f]/ based on:
    wschar →  ● /[ \t\n\v\f]/
    _$ebnf$1 → _$ebnf$1 ● wschar
    _ →  ● _$ebnf$1
    drop_statement → keyword ● _ option _ everything_else _ terminator
A character matching /[A-z]/ based on:
    option$ebnf$1 →  ● /[A-z]/
    option →  ● option$ebnf$1
    drop_statement → keyword _ ● option _ everything_else _ terminator

    at Parser.feed (/home/joe/code/me/sql-lint/node_modules/nearley/lib/nearley.js:317:27)
    at Drop.tokenise (/home/joe/code/me/sql-lint/dist/src/parser/statements/drop/drop.js:43:28)
    at Object.tokenise (/home/joe/code/me/sql-lint/dist/src/parser/lexer.js:21:22)
    at /home/joe/code/me/sql-lint/dist/src/checker/checkerRunner.js:38:43
    at Array.forEach (<anonymous>)
    at CheckerRunner.run (/home/joe/code/me/sql-lint/dist/src/checker/checkerRunner.js:34:20)
    at Object.<anonymous> (/home/joe/code/me/sql-lint/dist/src/main.js:60:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32) {
  offset: 5,
  token: { value: ';' }
}
```

This is pretty useful to me but not to the end user. Ideally it would bring back something like

```
sql-lint was unable to parse the statement. 
DROP ;

The syntax could be invalid or unexpected.
If you think this is a bug, post an issue on the sql-lint page:
https://github.com/joereynolds/sql-lint
```

**Comment by joereynolds** [comment]
Non issue, not using nearley for this.
