### ISSUE TITLE
Linting from stdin does not work on node >= 12

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/gauxilium#138]
Easy to test

(In the root of sql-lint)
`nvm install 12`
`nvm use 12`
`npm run build && ./dist/src/main.js`

Will error out with:

```
: ./dist/src/main.js
internal/fs/utils.js:230
    throw err;
    ^

Error: EAGAIN: resource temporarily unavailable, read
    at Object.readSync (fs.js:564:3)
    at tryReadSync (fs.js:349:20)
    at Object.readFileSync (fs.js:386:19)
    at Object.<anonymous> (/home/joe/code/me/sql-lint/dist/src/main.js:65:44)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -11,
  syscall: 'read',
  code: 'EAGAIN'
}
```

Not sure what the issue is but we should also add newer versions of node to the travis build

**Comment by joereynolds** [comment]
After all the updates, this seems to have been resolved

**Comment by joereynolds** [comment]
Not resolved, it'll die if no args are supplied
i.e.
`./dist/src/main,js`

**Comment by joereynolds** [comment]
https://github.com/joereynolds/sql-lint/commit/e77b6bad74c1d90d91d6b5f1858486a5b91cbdd3
