### ISSUE TITLE
Omit stack trace on query parse errors

### ISSUE THREAD

**Issue by felipecrs** [joereynolds/gauxilium#175]
Current:

```sh-session
❯ sql-lint .
/home/zdecfel/.nvm/versions/node/v14.15.1/lib/node_modules/sql-lint/dist/src/lexer/lexer.js:14
    throw new Error(`Unable to categorise query: ${query}. The query must start with one of ${Object.keys(keywords_1.Keyword)}`);
    ^

Error: Unable to categorise query: commit;. The query must start with one of Alter,Begin,Call,Create,Declare,Delete,Delimiter,Drop,Else,End,From,Having,If,Insert,Join,Leave,Limit,Replace,Return,Select,Set,Show,Truncate,Update,Use,Where,CommentHash,CommentDash,CommentMultiLineStart,CommentMultiLineEnd,Newline,WindowsNewline
    at Object.categorise (/home/zdecfel/.nvm/versions/node/v14.15.1/lib/node_modules/sql-lint/dist/src/lexer/lexer.js:14:11)
    at /home/zdecfel/.nvm/versions/node/v14.15.1/lib/node_modules/sql-lint/dist/src/checker/checkerRunner.js:38:42
    at Array.forEach (<anonymous>)
    at CheckerRunner.run (/home/zdecfel/.nvm/versions/node/v14.15.1/lib/node_modules/sql-lint/dist/src/checker/checkerRunner.js:35:20)
    at /home/zdecfel/.nvm/versions/node/v14.15.1/lib/node_modules/sql-lint/dist/src/main.js:78:20
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/zdecfel/.nvm/versions/node/v14.15.1/lib/node_modules/sql-lint/dist/src/main.js:76:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

Expected:

```sh-session
❯ sql-lint .
Error: Unable to categorise query: commit;. The query must start with one of Alter,Begin,Call,Create,Declare,Delete,Delimiter,Drop,Else,End,From,Having,If,Insert,Join,Leave,Limit,Replace,Return,Select,Set,Show,Truncate,Update,Use,Where,CommentHash,CommentDash,CommentMultiLineStart,CommentMultiLineEnd,Newline,WindowsNewline
```

**Comment by joereynolds** [comment]
Hey @felipecrs,

What version of `sql-lint` are you on?
I fixed this a while ago, can you try the latest version (0.0.15)?

Thanks!

**Comment by felipecrs** [comment]
I was already using the latest version:

```console
❯ sql-lint --driver postgres file.sql
/home/zdecfel/.nvm/versions/node/v14.15.2/lib/node_modules/sql-lint/dist/src/lexer/lexer.js:14
    throw new Error(`Unable to categorise query: ${query}. The query must start with one of ${Object.keys(keywords_1.Keyword)}`);
    ^

Error: Unable to categorise query: commit;. The query must start with one of Alter,Begin,Call,Create,Declare,Delete,Delimiter,Drop,Else,End,From,Having,If,Insert,Join,Leave,Limit,Replace,Return,Select,Set,Show,Truncate,Update,Use,Where,CommentHash,CommentDash,CommentMultiLineStart,CommentMultiLineEnd,Newline,WindowsNewline
    at Object.categorise (/home/zdecfel/.nvm/versions/node/v14.15.2/lib/node_modules/sql-lint/dist/src/lexer/lexer.js:14:11)
    at /home/zdecfel/.nvm/versions/node/v14.15.2/lib/node_modules/sql-lint/dist/src/checker/checkerRunner.js:38:42
    at Array.forEach (<anonymous>)
    at CheckerRunner.run (/home/zdecfel/.nvm/versions/node/v14.15.2/lib/node_modules/sql-lint/dist/src/checker/checkerRunner.js:35:20)
    at Object.<anonymous> (/home/zdecfel/.nvm/versions/node/v14.15.2/lib/node_modules/sql-lint/dist/src/main.js:86:8)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
❯ sql-lint --version
0.0.15
```

**Comment by joereynolds** [comment]
My bad, I know what the issue is. 
This was put in *after* 0.0.15, you can try building it from source or just wait until I bundle it in the next release. I can't say when that will be though.

**Comment by felipecrs** [comment]
No problem, thanks for the support!
