### ISSUE TITLE
Use check is broken on actual usage

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/gauxilium#19]
```
: sql-lint --query="use test"
undefined
CheckerResult { line: 0, content: '', tokens: '' }
CheckerResult {
  line: 0,
  content: 'Delete missing WHERE, intentional?',
  tokens: '' }
/home/joe/go/src/github.com/joereynolds/gauxilium/dist/src/checker/Use_DatabaseNotFound.js:11
        if (!this.db.getDatabases(this.db.connection).includes(tableReference)) {
                                                     ^

TypeError: Cannot read property 'includes' of undefined
    at DatabaseNotFound.check (/home/joe/go/src/github.com/joereynolds/gauxilium/dist/src/checker/Use_DatabaseNotFound.js:11:54)
    at checks.forEach (/home/joe/go/src/github.com/joereynolds/gauxilium/dist/src/main.js:45:27)
    at Array.forEach (<anonymous>)
    at allChecks.forEach (/home/joe/go/src/github.com/joereynolds/gauxilium/dist/src/main.js:44:12)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/joe/go/src/github.com/joereynolds/gauxilium/dist/src/main.js:43:11)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)

```

**Comment by joereynolds** [comment]
https://github.com/joereynolds/sql-lint/commit/0b929bf8c7a020c48f55bded4361eae71d2e6337
