### ISSUE TITLE
Catch when it tries to open an invalid file.

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/gauxilium#38]
At the moment it spits out loads of exceptions etc... Clean this up

Go from this

```
~/programs/sql-lint (typescript)
: sql-lint --file test/test-files/
fs.js:675
  return binding.read(fd, buffer, offset, length, position);
                 ^

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at Object.getQueryFromFile (/home/joe/programs/sql-lint/dist/src/reader/reader.js:29:25)
    at Object.<anonymous> (/home/joe/programs/sql-lint/dist/src/main.js:36:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

To this

```
Can't open file ${file}, does it exist?
```

**Comment by joereynolds** [comment]
https://github.com/joereynolds/sql-lint/commit/db282545486183a04e04899026352fd4409d8d72
